# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: "test_postgres"
    ports:
      - "54320:5432"
    volumes:
      - testpos_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "test"
volumes:
  testpos_dbdata:

  